/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminComponentsComponentIdEditRouteImport } from './routes/admin.components.$componentId.edit'
import { Route as AdminBoardsBoardIdEditRouteImport } from './routes/admin.boards.$boardId.edit'

const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComponentsComponentIdEditRoute =
  AdminComponentsComponentIdEditRouteImport.update({
    id: '/components/$componentId/edit',
    path: '/components/$componentId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBoardsBoardIdEditRoute = AdminBoardsBoardIdEditRouteImport.update({
  id: '/boards/$boardId/edit',
  path: '/boards/$boardId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/boards/$boardId/edit': typeof AdminBoardsBoardIdEditRoute
  '/admin/components/$componentId/edit': typeof AdminComponentsComponentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/boards/$boardId/edit': typeof AdminBoardsBoardIdEditRoute
  '/admin/components/$componentId/edit': typeof AdminComponentsComponentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/boards/$boardId/edit': typeof AdminBoardsBoardIdEditRoute
  '/admin/components/$componentId/edit': typeof AdminComponentsComponentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/docs'
    | '/examples'
    | '/admin/'
    | '/admin/boards/$boardId/edit'
    | '/admin/components/$componentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/examples'
    | '/admin'
    | '/admin/boards/$boardId/edit'
    | '/admin/components/$componentId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/docs'
    | '/examples'
    | '/admin/'
    | '/admin/boards/$boardId/edit'
    | '/admin/components/$componentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocsRoute: typeof DocsRoute
  ExamplesRoute: typeof ExamplesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/components/$componentId/edit': {
      id: '/admin/components/$componentId/edit'
      path: '/components/$componentId/edit'
      fullPath: '/admin/components/$componentId/edit'
      preLoaderRoute: typeof AdminComponentsComponentIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/boards/$boardId/edit': {
      id: '/admin/boards/$boardId/edit'
      path: '/boards/$boardId/edit'
      fullPath: '/admin/boards/$boardId/edit'
      preLoaderRoute: typeof AdminBoardsBoardIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBoardsBoardIdEditRoute: typeof AdminBoardsBoardIdEditRoute
  AdminComponentsComponentIdEditRoute: typeof AdminComponentsComponentIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBoardsBoardIdEditRoute: AdminBoardsBoardIdEditRoute,
  AdminComponentsComponentIdEditRoute: AdminComponentsComponentIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DocsRoute: DocsRoute,
  ExamplesRoute: ExamplesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
